include!("tests/part01a.rs");
include!("tests/part01c.rs");
include!("tests/part01b.rs");
include!("tests/part02a.rs");
include!("tests/part02b.rs");
include!("tests/part03.rs");
include!("tests/part04.rs");
include!("tests/part05.rs");
include!("tests/part06.rs");
