use super::{
    warn, ConnectionTimeline, IpPacket, Ipv4Packet, OutboundPacket, PeerManager, PeerPendingQueue,
    Protocol, WireGuardTransport, REASON_OUTBOUND_QUEUE_FULL,
};

/// Extract the identity of an overlay harness packet for diagnostics only.
/// This never drives routing or delivery; it lets a failed burst correlate
/// the raw TUN ingress with the encrypted transport outcome without logging
/// payload bytes.
pub(super) fn overlay_packet_identity(packet: &[u8]) -> Option<(u64, u32, u8)> {
    let ip = Ipv4Packet::new(packet).ok()?;
    if ip.protocol() != Protocol::Udp {
        return None;
    }
    let udp_payload = ip.payload().get(8..)?;
    let payload = udp_payload.strip_prefix(crate::OVERLAY_PAYLOAD_MAGIC)?;
    let direction = *payload.first()?;
    let nonce = u64::from_be_bytes(payload.get(1..9)?.try_into().ok()?);
    let sequence = u32::from_be_bytes(payload.get(9..13)?.try_into().ok()?);
    Some((nonce, sequence, direction))
}

/// Return a payload-free description of a raw TUN packet for queue diagnostics.
/// The real daemon can receive packets generated by the host OS or another
/// process before the acceptance harness sends its own echo.  Recording only
/// L3/L4 headers lets us identify that source without putting user payloads,
/// credentials, or packet contents into logs/artifacts.
pub(super) fn raw_packet_summary(packet: &[u8]) -> String {
    let Ok(ip) = Ipv4Packet::new(packet) else {
        return format!("unparsed bytes={}", packet.len());
    };
    let protocol = ip.protocol();
    let mut summary = format!(
        "proto={} src={} dst={} bytes={}",
        protocol,
        ip.src_addr(),
        ip.dst_addr(),
        packet.len()
    );
    let payload = ip.payload();
    match protocol {
        Protocol::Tcp | Protocol::Udp if payload.len() >= 4 => {
            let source_port = u16::from_be_bytes([payload[0], payload[1]]);
            let destination_port = u16::from_be_bytes([payload[2], payload[3]]);
            summary.push_str(&format!(
                " src_port={source_port} dst_port={destination_port}"
            ));
        }
        Protocol::Icmp if payload.len() >= 2 => {
            summary.push_str(&format!(
                " icmp_type={} icmp_code={}",
                payload[0], payload[1]
            ));
        }
        _ => {}
    }
    summary
}

pub(super) fn complete_inner_ip_packet_len(packet: &[u8]) -> Option<usize> {
    let parsed = IpPacket::new(packet).ok()?;
    let total_len = parsed.total_len();
    (total_len == packet.len()).then_some(total_len)
}

/// Count a queue-overflow loss structurally and emit the timeline event.
pub(super) async fn record_overflow_drop(
    peers: &PeerManager,
    peer_id: &str,
    dropped_packets: usize,
    dropped_bytes: usize,
    entry: &PeerPendingQueue,
    timeline: &ConnectionTimeline,
) {
    peers
        .record_outbound_drop(REASON_OUTBOUND_QUEUE_FULL, dropped_packets, dropped_bytes)
        .await;
    record_loss_event(
        peers,
        "drop",
        peer_id,
        entry
            .wait_generation
            .unwrap_or_else(|| peers.current_network_generation_sync()),
        REASON_OUTBOUND_QUEUE_FULL,
        dropped_packets,
        dropped_bytes,
        timeline,
    )
    .await;
    timeline.emit(
        "outbound_packet_dropped",
        None,
        Some(REASON_OUTBOUND_QUEUE_FULL),
        Some(format!(
            "peer={peer_id} dropped={dropped_packets} bytes={dropped_bytes} reason={REASON_OUTBOUND_QUEUE_FULL} queued={} queued_bytes={} queue_head={}",
            entry.queue.len(),
            entry.bytes,
            entry
                .queue
                .front()
                .map(|packet| raw_packet_summary(packet.raw_packet()))
                .unwrap_or_else(|| "empty".to_string())
        )),
    );
}

#[allow(clippy::too_many_arguments)]
pub(super) async fn record_terminal_drop(
    transport: &WireGuardTransport,
    peers: &PeerManager,
    peer_id: &str,
    packet_generation: u64,
    packet: OutboundPacket,
    reason_code: &'static str,
    reason: String,
    timeline: &ConnectionTimeline,
) {
    let bytes = packet.packet.len();
    record_terminal_drop_bytes(
        transport,
        peers,
        peer_id,
        packet_generation,
        bytes,
        reason_code,
        reason,
        timeline,
    )
    .await;
}

#[allow(clippy::too_many_arguments)]
pub(super) async fn record_terminal_drop_bytes(
    transport: &WireGuardTransport,
    peers: &PeerManager,
    peer_id: &str,
    packet_generation: u64,
    bytes: usize,
    reason_code: &'static str,
    reason: String,
    timeline: &ConnectionTimeline,
) {
    transport.record_outbound_drop(reason_code, 1, bytes).await;
    record_loss_event(
        peers,
        "drop",
        peer_id,
        packet_generation,
        reason_code,
        1,
        bytes,
        timeline,
    )
    .await;
    timeline.emit(
        "outbound_packet_dropped",
        None,
        Some(reason_code),
        Some(format!(
            "peer={peer_id} generation={packet_generation} dropped=1 bytes={bytes} detail={reason}"
        )),
    );
    warn!(
        event = "outbound_terminal_drop",
        peer_id = %peer_id,
        generation = packet_generation,
        reason_code,
        packets = 1u64,
        bytes,
        detail = %reason,
        "plaintext business packet reached a terminal loss boundary"
    );
}

#[allow(clippy::too_many_arguments)]
pub(super) async fn record_loss_event(
    peers: &PeerManager,
    kind: &str,
    peer_id: &str,
    generation: u64,
    reason_code: &str,
    packets: usize,
    bytes: usize,
    timeline: &ConnectionTimeline,
) {
    peers
        .record_outbound_loss_event(crate::peer::OutboundLossEvent {
            kind: kind.to_string(),
            peer_id: peer_id.to_string(),
            generation,
            reason_code: reason_code.to_string(),
            packets: packets as u64,
            bytes: bytes as u64,
            correlation_id: timeline.correlation_id().to_string(),
            at_ms: timeline.uptime_ms(),
        })
        .await;
}
