use super::*;

/// Extract the identity of an overlay harness packet for diagnostics only.
/// This never drives routing or delivery; it lets a failed burst correlate
/// the raw TUN ingress with the encrypted transport outcome without logging
/// payload bytes.
pub(super) fn overlay_packet_identity(packet: &[u8]) -> Option<(u64, u32, u8)> {
    let ip = Ipv4Packet::new(packet).ok()?;
    if ip.protocol() != Protocol::Udp {
        return None;
    }
    let udp_payload = ip.payload().get(8..)?;
    let payload = udp_payload.strip_prefix(crate::OVERLAY_PAYLOAD_MAGIC)?;
    let direction = *payload.first()?;
    let nonce = u64::from_be_bytes(payload.get(1..9)?.try_into().ok()?);
    let sequence = u32::from_be_bytes(payload.get(9..13)?.try_into().ok()?);
    Some((nonce, sequence, direction))
}

/// Return a payload-free description of a raw TUN packet for queue diagnostics.
/// The real daemon can receive packets generated by the host OS or another
/// process before the acceptance harness sends its own echo.  Recording only
/// L3/L4 headers lets us identify that source without putting user payloads,
/// credentials, or packet contents into logs/artifacts.
pub(super) fn raw_packet_summary(packet: &[u8]) -> String {
    let Ok(ip) = Ipv4Packet::new(packet) else {
        return format!("unparsed bytes={}", packet.len());
    };
    let protocol = ip.protocol();
    let mut summary = format!(
        "proto={} src={} dst={} bytes={}",
        protocol,
        ip.src_addr(),
        ip.dst_addr(),
        packet.len()
    );
    let payload = ip.payload();
    match protocol {
        Protocol::Tcp | Protocol::Udp if payload.len() >= 4 => {
            let source_port = u16::from_be_bytes([payload[0], payload[1]]);
            let destination_port = u16::from_be_bytes([payload[2], payload[3]]);
            summary.push_str(&format!(
                " src_port={source_port} dst_port={destination_port}"
            ));
        }
        Protocol::Icmp if payload.len() >= 2 => {
            summary.push_str(&format!(
                " icmp_type={} icmp_code={}",
                payload[0], payload[1]
            ));
        }
        _ => {}
    }
    summary
}

pub(super) fn complete_inner_ip_packet_len(packet: &[u8]) -> Option<usize> {
    let parsed = IpPacket::new(packet).ok()?;
    let total_len = parsed.total_len();
    (total_len == packet.len()).then_some(total_len)
}

#[allow(clippy::too_many_arguments)]
pub(super) async fn record_loss_event(
    peers: &PeerManager,
    kind: &str,
    peer_id: &str,
    generation: u64,
    reason_code: &str,
    packets: usize,
    bytes: usize,
    timeline: &ConnectionTimeline,
) {
    peers
        .record_outbound_loss_event(crate::peer::OutboundLossEvent {
            kind: kind.to_string(),
            peer_id: peer_id.to_string(),
            generation,
            reason_code: reason_code.to_string(),
            packets: packets as u64,
            bytes: bytes as u64,
            correlation_id: timeline.correlation_id().to_string(),
            at_ms: timeline.uptime_ms(),
        })
        .await;
}
