#!/usr/bin/env python3
"""Format-check the Rust sources that ``cargo fmt`` cannot reach.

``rustfmt`` follows ``mod`` declarations, not ``include!`` macros. Every file
this crate pulls in with ``include!`` is therefore invisible to
``cargo fmt --all --check``: the gate reports success while those files are
never inspected. That blind spot is what let the two former ``part03`` /
``part07`` test files accumulate formatting drift for as long as they did.

This checker discovers the include! graph from each crate's own sources, runs
``rustfmt --check`` on every file it reaches, and compares the result with a
recorded baseline. The baseline exists because the debt is large and was
inherited, not because the files are exempt:

* a file that is **not** in the baseline must be formatted;
* a file that **is** in the baseline must still be unformatted, so the list can
  only shrink -- formatting one and leaving the entry behind fails the gate.

Generated sources are excluded by an explicit marker rather than by guesswork.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[2]
BASELINE = ROOT / "scripts/quality/include_format_baseline.txt"
INCLUDE = re.compile(r'include!\(\s*"([^"]+)"\s*\)')
GENERATED_MARKERS = ("@generated", "Code generated by", "DO NOT EDIT")
SKIP_DIRS = {".git", "target", "node_modules", ".dart_tool", "build"}


class FormatCheckError(RuntimeError):
    """The check could not be completed; the caller must not read this as pass."""


def _label(path: Path) -> str:
    """A stable name for messages, even for paths outside the repository."""
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def workspace_edition(root: Path = ROOT) -> str:
    """The edition every crate compiles with, taken from the workspace manifest."""
    manifest = root / "Cargo.toml"
    try:
        text = manifest.read_text(encoding="utf-8")
    except OSError as error:
        raise FormatCheckError(f"cannot read {manifest}: {error}") from error
    match = re.search(r"^\[workspace\.package\]$(.*?)(?=^\[|\Z)", text, re.M | re.S)
    scope = match.group(1) if match else text
    edition = re.search(r'^edition\s*=\s*"([^"]+)"', scope, re.M)
    if edition is None:
        raise FormatCheckError("the workspace manifest declares no edition")
    return edition.group(1)


def _is_generated(path: Path) -> bool:
    if "generated" in {part.lower() for part in path.parts}:
        return True
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:2048]
    except OSError:
        return False
    return any(marker in head for marker in GENERATED_MARKERS)


def include_targets(root: Path = ROOT) -> dict[Path, Path]:
    """Map every include! target to one file that includes it."""
    sources = [
        path
        for path in root.rglob("*.rs")
        if not any(part in SKIP_DIRS for part in path.relative_to(root).parts)
    ]
    targets: dict[Path, Path] = {}
    pending = list(sources)
    seen_sources: set[Path] = set()
    while pending:
        source = pending.pop()
        if source in seen_sources:
            continue
        seen_sources.add(source)
        try:
            text = source.read_text(encoding="utf-8", errors="replace")
        except OSError as error:
            raise FormatCheckError(f"cannot read {source}: {error}") from error
        for match in INCLUDE.finditer(text):
            target = (source.parent / match.group(1)).resolve()
            if not target.is_file():
                raise FormatCheckError(f"{source} includes a missing file: {match.group(1)}")
            if target not in targets:
                targets[target] = source
                pending.append(target)
    return targets


def classify(targets: Iterable[Path], edition: str) -> tuple[list[Path], list[Path]]:
    """Split the targets into (unformatted, not-standalone).

    ``not-standalone`` covers the include! targets that are syntactic fragments
    (for example a ``match`` body spliced into the middle of a function). They
    are parsed only in their including context, so rustfmt cannot check them on
    their own; they are recorded rather than silently skipped.
    """
    dirty: list[Path] = []
    fragments: list[Path] = []
    for target in sorted(targets):
        if _is_generated(target):
            continue
        result = subprocess.run(
            ["rustfmt", "--edition", edition, "--check", str(target)],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            continue
        # rustfmt exits 1 both for "would reformat" and for a file it cannot
        # parse. Only the former is drift; a parse failure must not be filed
        # away as formatting debt.
        if result.returncode == 1 and "error:" not in result.stderr:
            dirty.append(target)
            continue
        if result.returncode == 1 and "expected item, found" in result.stderr:
            fragments.append(target)
            continue
        raise FormatCheckError(
            f"rustfmt could not check {_label(target)} (exit {result.returncode}): "
            + (result.stderr.strip() or "<no stderr>")
        )
    return dirty, fragments


def read_baseline(path: Path = BASELINE) -> dict[str, set[str]]:
    """Read ``{kind: {path}}``; kinds are ``drift`` and ``fragment``."""
    summary: dict[str, set[str]] = {"drift": set(), "fragment": set()}
    if not path.is_file():
        return summary
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        kind, _, name = line.partition(" ")
        if kind not in summary:
            raise FormatCheckError(f"{path}: unknown baseline kind {kind!r}")
        summary[kind].add(name.strip())
    return summary


def compare(
    dirty: Iterable[Path], fragments: Iterable[Path], baseline: dict[str, set[str]]
) -> list[str]:
    errors: list[str] = []
    for kind, paths in (("drift", dirty), ("fragment", fragments)):
        relative = {path.relative_to(ROOT).as_posix() for path in paths}
        known = baseline[kind]
        if kind == "drift":
            errors += [
                f"{name}: not formatted; run rustfmt --edition <edition> on it"
                for name in sorted(relative - known)
            ]
            errors += [
                f"{name}: recorded as unformatted but is now formatted; drop it from the baseline"
                for name in sorted(known - relative)
            ]
        else:
            errors += [
                f"{name}: is a standalone parseable file now; move it to the drift list"
                for name in sorted(known - relative)
            ]
            errors += [
                f"{name}: new include! fragment that rustfmt cannot parse; record it explicitly"
                for name in sorted(relative - known)
            ]
    return errors


def write_baseline(
    dirty: Iterable[Path], fragments: Iterable[Path], path: Path = BASELINE, root: Path = ROOT
) -> None:
    drift = sorted(target.relative_to(root).as_posix() for target in dirty)
    frags = sorted(target.relative_to(root).as_posix() for target in fragments)
    header = (
        "# Rust sources reached through include! that `cargo fmt --all --check` cannot see.\n"
        "# cargo fmt follows `mod`, not `include!`, so rustfmt never inspected these.\n"
        "#   drift <path>    -> rustfmt would rewrite it today (inherited drift)\n"
        "#   fragment <path> -> a syntactic fragment spliced into another item;\n"
        "#                      rustfmt can only parse it in that context\n"
        "# Neither list is an exemption: both may only shrink. Format a drift entry\n"
        "# and drop it; if a fragment becomes a standalone file, move it to drift.\n"
        f"# {len(drift)} drift, {len(frags)} fragment.\n"
    )
    body = "".join(f"drift {name}\n" for name in drift) + "".join(
        f"fragment {name}\n" for name in frags
    )
    path.write_text(header + body, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update-baseline", action="store_true")
    args = parser.parse_args(argv)
    try:
        edition = workspace_edition()
        targets = include_targets()
        dirty, fragments = classify(targets, edition)
    except FormatCheckError as error:
        print(f"FAIL include format: {error}", file=sys.stderr)
        return 1

    if args.update_baseline:
        write_baseline(dirty, fragments)
        print(
            f"recorded {len(dirty)} unformatted and {len(fragments)} fragment "
            f"include! sources in {BASELINE.name}"
        )
        return 0

    baseline = read_baseline()
    errors = compare(dirty, fragments, baseline)
    if errors:
        print("FAIL include format")
        for error in errors:
            print(f"- {error}")
        return 1
    print(
        f"PASS include format ({len(targets)} include! sources checked with edition {edition}; "
        f"{len(baseline['drift'])} recorded as inherited drift, "
        f"{len(baseline['fragment'])} recorded as fragments)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
