[package]
name = "p2wlan-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
p2pnet-nat = { path = "../client/nat" }

[[bin]]
name = "pnch_parser"
path = "fuzz_targets/pnch_parser.rs"
test = false
doc = false
bench = false

[workspace]
