import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import check_include_format as fmt

# Deliberately not what rustfmt would produce.
UNFORMATTED = 'pub fn  sample( )->i32{\n1\n}\n'
MALFORMED = "fn broken( {\n"


class CompareTests(unittest.TestCase):
    def _path(self, name):
        return fmt.ROOT / name

    def test_unrecorded_drift_fails(self):
        errors = fmt.compare([self._path("client/daemon/src/new.rs")], [], {"drift": set(), "fragment": set()})
        self.assertEqual(len(errors), 1)
        self.assertIn("not formatted", errors[0])

    def test_recorded_drift_passes(self):
        errors = fmt.compare(
            [self._path("client/daemon/src/old.rs")], [], {"drift": {"client/daemon/src/old.rs"}, "fragment": set()}
        )
        self.assertEqual(errors, [])

    def test_baseline_must_shrink_when_a_file_is_formatted(self):
        errors = fmt.compare([], [], {"drift": {"client/daemon/src/fixed.rs"}, "fragment": set()})
        self.assertEqual(len(errors), 1)
        self.assertIn("drop it from the baseline", errors[0])

    def test_new_fragment_must_be_recorded_explicitly(self):
        errors = fmt.compare([], [self._path("client/daemon/src/commands.rs")], {"drift": set(), "fragment": set()})
        self.assertEqual(len(errors), 1)
        self.assertIn("fragment", errors[0])

    def test_fragment_that_becomes_standalone_must_move_to_drift(self):
        errors = fmt.compare([], [], {"drift": set(), "fragment": {"client/daemon/src/commands.rs"}})
        self.assertEqual(len(errors), 1)
        self.assertIn("move it to the drift list", errors[0])


class DiscoveryTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def write(self, relative, text):
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        return path

    def test_targets_are_discovered_through_nested_includes(self):
        self.write("src/entry.rs", 'include!("parts/one.rs");\n')
        self.write("src/parts/one.rs", 'include!("nested/two.rs");\n')
        target = self.write("src/parts/nested/two.rs", "pub fn two() {}\n")
        found = fmt.include_targets(self.root)
        self.assertIn(target.resolve(), found)

    def test_missing_include_target_fails_closed(self):
        self.write("src/entry.rs", 'include!("gone.rs");\n')
        with self.assertRaises(fmt.FormatCheckError):
            fmt.include_targets(self.root)

    def test_generated_files_are_excluded_by_marker(self):
        generated = self.write("src/gen.rs", "// Code generated by tool. DO NOT EDIT.\n" + UNFORMATTED)
        self.assertTrue(fmt._is_generated(generated))

    def test_generated_directory_is_excluded(self):
        self.assertTrue(fmt._is_generated(self.root / "src/generated/thing.rs"))

    def test_unformatted_include_target_is_reported(self):
        self.write("src/entry.rs", 'include!("ugly.rs");\n')
        ugly = self.write("src/ugly.rs", UNFORMATTED)
        dirty, fragments = fmt.classify([ugly], "2021")
        self.assertEqual(dirty, [ugly])
        self.assertEqual(fragments, [])

    def test_formatted_include_target_is_clean(self):
        clean = self.write("src/fine.rs", "pub fn sample() -> i32 {\n    1\n}\n")
        dirty, fragments = fmt.classify([clean], "2021")
        self.assertEqual((dirty, fragments), ([], []))

    def test_malformed_target_is_not_filed_as_formatting_drift(self):
        broken = self.write("src/broken.rs", MALFORMED)
        with self.assertRaises(fmt.FormatCheckError):
            fmt.classify([broken], "2021")

    def test_fragment_is_recorded_separately_rather_than_skipped(self):
        fragment = self.write("src/commands.rs", "match cmd {\n    _ => {}\n}\n")
        dirty, fragments = fmt.classify([fragment], "2021")
        self.assertEqual(dirty, [])
        self.assertEqual(fragments, [fragment])

    def test_baseline_round_trips(self):
        baseline = self.root / "baseline.txt"
        fmt.write_baseline(
            [self.write("src/a.rs", UNFORMATTED)],
            [self.write("src/b.rs", MALFORMED)],
            baseline,
            root=self.root,
        )
        read = fmt.read_baseline(baseline)
        self.assertEqual(read["drift"], {"src/a.rs"})
        self.assertEqual(read["fragment"], {"src/b.rs"})

    def test_unknown_baseline_kind_is_rejected(self):
        baseline = self.root / "baseline.txt"
        baseline.write_text("typo src/a.rs\n", encoding="utf-8")
        with self.assertRaises(fmt.FormatCheckError):
            fmt.read_baseline(baseline)

    def test_item_file_spliced_by_include_is_not_a_fragment(self):
        """The shape a stand-alone include! item file has.

        `runtime/commands.rs` used to be a bare `match` statement and could only
        be parsed inside its including function. It is now an `enum` plus an
        `async fn`, which rustfmt must check as an ordinary file rather than
        file away as an unparseable fragment.
        """
        item = self.write(
            "src/commands.rs",
            "enum Disposition {\n    Continue,\n}\n\nasync fn handle() -> Disposition {\n    Disposition::Continue\n}\n",
        )
        subprocess.run(
            ["rustfmt", "--edition", "2021", str(item)], check=True, capture_output=True
        )
        dirty, fragments = fmt.classify([item], "2021")
        self.assertEqual(fragments, [], "an item file must not be recorded as a fragment")
        self.assertEqual(dirty, [])

    def test_a_new_unformatted_include_target_is_reported_from_disk(self):
        self.write("Cargo.toml", '[workspace.package]\nedition = "2021"\n')
        self.write("src/entry.rs", 'include!("ugly.rs");\n')
        ugly = self.write("src/ugly.rs", UNFORMATTED)
        dirty, fragments = fmt.classify(
            fmt.include_targets(self.root), fmt.workspace_edition(self.root)
        )
        self.assertEqual(fragments, [])
        self.assertEqual(dirty, [ugly.resolve()])

    def test_a_new_malformed_include_target_fails_closed_from_disk(self):
        self.write("Cargo.toml", '[workspace.package]\nedition = "2021"\n')
        self.write("src/entry.rs", 'include!("broken.rs");\n')
        self.write("src/broken.rs", MALFORMED)
        with self.assertRaises(fmt.FormatCheckError):
            fmt.classify(
                fmt.include_targets(self.root), fmt.workspace_edition(self.root)
            )


class RepositoryBaselineTests(unittest.TestCase):
    def test_no_include_debt_is_recorded_in_the_repository(self):
        """The ratchet that makes the baseline non-escapable.

        `compare` already fails on an unformatted file that is not recorded, so
        an empty checked-in baseline means every include! source the repository
        reaches is formatted today. Recording a new exemption therefore means
        editing this test, which is visible in review; a cleared historical
        fragment cannot quietly come back.
        """
        recorded = fmt.read_baseline(fmt.BASELINE)
        self.assertEqual(
            recorded["drift"],
            set(),
            "format the file with rustfmt instead of re-recording it",
        )
        self.assertEqual(
            recorded["fragment"],
            set(),
            "an include! fragment must stay converted into a stand-alone item file",
        )


class EditionTests(unittest.TestCase):
    def test_workspace_edition_is_read(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "Cargo.toml").write_text(
                '[workspace.package]\nedition = "2024"\n', encoding="utf-8"
            )
            self.assertEqual(fmt.workspace_edition(root), "2024")

    def test_missing_edition_fails_closed(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "Cargo.toml").write_text("[workspace]\nmembers = []\n", encoding="utf-8")
            with self.assertRaises(fmt.FormatCheckError):
                fmt.workspace_edition(root)

    def test_repository_declares_an_edition(self):
        self.assertTrue(fmt.workspace_edition())


if __name__ == "__main__":
    unittest.main()
