[package]
name = "p2wlan-tray"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Tiny native tray controller for P2WLAN"

[dependencies]
p2wlan-desktop-host = { path = "../desktop-host" }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = { workspace = true }
tao = "0.35.3"
tray-icon = { version = "0.24.1", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
tray-icon = { version = "0.24.1" }

[target.'cfg(target_os = "windows")'.dependencies]
tray-icon = { version = "0.24.1", default-features = false, features = ["common-controls-v6"] }
