[package]
name = "p2wlan-tray"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Tiny native tray controller for P2WLAN"

[dependencies]
arboard = { version = "3.6.1", default-features = false }
p2wlan-desktop-host = { path = "../desktop-host", version = "0.1.147" }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
trayicon = "0.4.1"
winit = "0.30.13"
